name: Infrastructure Validation
 
on:
  pull_request:
    branches:
      - master
    paths:
      - "**.tf"
      - ".github/workflows/infra-check.yml"
 
permissions:
  contents: read
  pull-requests: write
 
jobs:
  infrastructure:
    name: Infrastructure
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
 
    steps:
      - name: Get code
        uses: actions/checkout@v4
 
      - name: Install IaC tool
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"
 
      - name: Code Format Verification
        id: format
        run: terraform fmt -check -recursive
        continue-on-error: false
 
      - name: Configuration Setup
        id: setup
        run: terraform init -backend=false
 
      - name: Configuration Verification
        id: verify
        run: terraform validate
 
      - name: Error Check
        if: steps.format.outcome == 'failure' || steps.verify.outcome == 'failure'
        run: exit 1